export const WORDS = [
  'AGENT',
  'WORLD',
  'ABOUT',
  'HEART',
  'WATER',
  'SIXTY',
  'BOARD',
  'MONTH',
  'MUSIC',
  'PARTY',
  'PIANO',
  'MOUTH',
  'WOMAN',
  'SUGAR',
  'AMBER',
  'DREAM',
  'LAUGH',
  'TIGER',
  'EARTH',
  'MONEY',
  'WORDS',
  'SMILE',
  'LEMON',
  'SOUTH',
  'AFTER',
  'STONE',
  'THING',
  'LIGHT',
  'STORY',
  'POWER',
  'TODAY',
  'RANGE',
  'PEARL',
  'VENOM',
  'PROXY',
  'ROUND',
  'HOVER',
  'CANDY',
  'ABOVE',
  'PHONE',
  'OTHER',
  'SMART',
  'BLACK',
  'MAGIC',
  'FRUIT',
  'RADIO',
  'ROYAL',
  'HONEY',
  'FLAKE',
  'SOUND',
];

// Keyboard characters
export const keyboardCharacters = [
  [
    { status: '', letter: 'Q' },
    { status: '', letter: 'W' },
    { status: '', letter: 'E' },
    { status: '', letter: 'R' },
    { status: '', letter: 'T' },
    { status: '', letter: 'Y' },
    { status: '', letter: 'U' },
    { status: '', letter: 'I' },
    { status: '', letter: 'O' },
    { status: '', letter: 'P' },
  ],
  [
    { status: '', letter: 'A' },
    { status: '', letter: 'S' },
    { status: '', letter: 'D' },
    { status: '', letter: 'F' },
    { status: '', letter: 'G' },
    { status: '', letter: 'H' },
    { status: '', letter: 'J' },
    { status: '', letter: 'K' },
    { status: '', letter: 'L' },
  ],
  [
    { status: '', letter: 'Z' },
    { status: '', letter: 'X' },
    { status: '', letter: 'C' },
    { status: '', letter: 'V' },
    { status: '', letter: 'B' },
    { status: '', letter: 'N' },
    { status: '', letter: 'M' },
  ],
];
